"""add_quality_score_geometry_h3

Revision ID: 43bd00f79d44
Revises: 
Create Date: 2026-02-21 14:13:11.098452

"""
from typing import Sequence, Union

import geoalchemy2
from alembic import op
import sqlalchemy as sa


revision: str = '43bd00f79d44'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grid_cells',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grid_index', sa.String(length=64), nullable=False),
    sa.Column('h3_resolution', sa.Integer(), nullable=False),
    sa.Column('geometry_center_lat', sa.Float(), nullable=False),
    sa.Column('geometry_center_lon', sa.Float(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grid_index', name='uq_grid_cells_index')
    )
    # Note: idx_grid_cells_geometry (GIST) is created automatically by
    # GeoAlchemy2 when the geometry column is added; no explicit op here.
    op.create_index('ix_grid_center', 'grid_cells', ['geometry_center_lat', 'geometry_center_lon'], unique=False)
    op.create_index('ix_grid_resolution', 'grid_cells', ['h3_resolution'], unique=False)
    op.create_table('raw_measurements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('device_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('server_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('bearing', sa.Float(), nullable=True),
    sa.Column('operator_id', sa.String(length=10), nullable=False),
    sa.Column('technology', sa.Enum('LTE', 'NR', name='technology'), nullable=False),
    sa.Column('cell_id', sa.BigInteger(), nullable=True),
    sa.Column('rsrp', sa.Float(), nullable=True),
    sa.Column('rsrq', sa.Float(), nullable=True),
    sa.Column('sinr', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('sample_weight', sa.Float(), nullable=True),
    sa.Column('is_cleaned', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_raw_is_cleaned', 'raw_measurements', ['is_cleaned'], unique=False)
    op.create_index('ix_raw_lat_lon', 'raw_measurements', ['lat', 'lon'], unique=False)
    op.create_index('ix_raw_operator_ts', 'raw_measurements', ['operator_id', 'server_timestamp'], unique=False)
    op.create_index('ix_raw_server_ts', 'raw_measurements', ['server_timestamp'], unique=False)
    op.create_table('grid_scores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('grid_cell_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.String(length=10), nullable=False),
    sa.Column('time_bucket', sa.DateTime(timezone=True), nullable=False),
    sa.Column('aggregated_rsrp', sa.Float(), nullable=True),
    sa.Column('aggregated_rsrq', sa.Float(), nullable=True),
    sa.Column('aggregated_sinr', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grid_cell_id'], ['grid_cells.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grid_cell_id', 'operator_id', 'time_bucket', name='uq_grid_scores_cell_op_bucket')
    )
    op.create_index('ix_grid_scores_cell_id', 'grid_scores', ['grid_cell_id'], unique=False)
    op.create_index('ix_grid_scores_operator_bucket', 'grid_scores', ['operator_id', 'time_bucket'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_grid_scores_operator_bucket', table_name='grid_scores')
    op.drop_index('ix_grid_scores_cell_id', table_name='grid_scores')
    op.drop_table('grid_scores')
    op.drop_index('ix_raw_server_ts', table_name='raw_measurements')
    op.drop_index('ix_raw_operator_ts', table_name='raw_measurements')
    op.drop_index('ix_raw_lat_lon', table_name='raw_measurements')
    op.drop_index('ix_raw_is_cleaned', table_name='raw_measurements')
    op.drop_table('raw_measurements')
    op.drop_index('ix_grid_resolution', table_name='grid_cells')
    op.drop_index('ix_grid_center', table_name='grid_cells')
    op.drop_index('idx_grid_cells_geometry', table_name='grid_cells', postgresql_using='gist')
    op.drop_table('grid_cells')
    # ### end Alembic commands ###
