"""add_qoe_mos_fitness_columns

Revision ID: 75073036bb82
Revises: 43bd00f79d44
Create Date: 2026-03-18 15:41:32.029132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '75073036bb82'
down_revision: Union[str, None] = '43bd00f79d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grid_scores', sa.Column('qoe_index', sa.Float(), nullable=True))
    op.add_column('grid_scores', sa.Column('estimated_mos', sa.Float(), nullable=True))
    op.add_column('grid_scores', sa.Column('fit_streaming', sa.Boolean(), nullable=True))
    op.add_column('grid_scores', sa.Column('fit_volte', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grid_scores', 'fit_volte')
    op.drop_column('grid_scores', 'fit_streaming')
    op.drop_column('grid_scores', 'estimated_mos')
    op.drop_column('grid_scores', 'qoe_index')
    # ### end Alembic commands ###
